#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_exit no_unset extended_glob pipe_fail warn_create_global

local min max
IFS=- read -r min max
[[ $min == <100000-999999> && $max == <100000-999999> ]]
local -i min max

local n
local -i res

for ((n = min; n <= max; ++n)); do
  [[ ${(j::)${(os::)n}} == $n ]] || continue
  [[ $n =~ '(.)\1' ]] || continue
  res+=1
done

echo -E - $res
