#!/usr/bin/env zsh

emulate -L zsh -o err_return -o no_unset

integer min max res
IFS=- read min max

(( min >= 100000 )) || min=100000
(( max <= 999999 )) || max=999999

local n
for ((n = min; n <= max; ++n)); do
  (( n[6] >= n[5] && n[5] >= n[4] && n[4] >= n[3] && n[3] >= n[2] && n[2] >= n[1] )) || continue
  [[ $n == *(11|22|33|44|55|66|77|88|99)* ]]                                         || continue
  (( ++res ))
done

echo - $res
