#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_return no_unset extended_glob pipe_fail warn_create_global warn_nested_var

local -A child2parent
local parent child

while IFS=')' read -r parent child; do
  [[ -n $parent && -n $child && ! -v child2parent[$child] ]]
  child2parent[$child]=$parent
done

local -A my_parents

local -i dist=0
local child=YOU
while [[ -v child2parent[$child] ]]; do
  local parent=$child2parent[$child]
  my_parents[$parent]=$((dist++))
  child=$parent
done

local -i dist=0
local child=SAN
while true; do
  local parent=$child2parent[$child]
  if [[ -v my_parents[$parent] ]]; then
    echo -E - $((dist + my_parents[$parent]))
    return 0
  fi
  (( ++dist ))
  child=$parent
done

return 1
