#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_return no_unset extended_glob pipe_fail warn_create_global

local n
local -i res

while read -r n; do
  [[ $n == <1-1000000> ]]
  while (( (n = n / 3 - 2) > 0 )); do
    (( (res += n) < 1 << 31 ))
  done
done

echo - $res
