#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_return no_unset extended_glob pipe_fail warn_create_global
setopt pushd_silent prompt_percent no_prompt_subst

(( ARGC )) || set -- ${ZSH_SCRIPT:h}/<->(/:t)

local task
for task; do
  [[ $task == <-> ]]
  pushd ${ZSH_SCRIPT:h}/$task
  print -rP -- "Solving %B$task%b..." >&2
  ./solve <input >answer
  print -rP -- "Answer for %B$task%b: %F{green}${(V)$(<answer)//\%//%%}%f" >&2
  popd
done
