#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_exit no_unset extended_glob pipe_fail warn_create_global

local -ri m=10007

local -i x=2019
local line match mbegin mend
while read -r line; do
  if [[ $line == 'deal into new stack' ]]; then
    (( x = (m + m - x - 1) % m, 1 ))
  elif [[ $line == (#b)'cut '((-|)<->) ]]; then
    (( x = (m + x - match[1]) % m, 1 ))
  elif [[ $line == (#b)'deal with increment '(<1->) ]]; then
    (( x = x * match[1] % m, 1 ))
  else
    exit 1
  fi
done

echo -E - $x
