#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_exit no_unset extended_glob pipe_fail warn_create_global

local line
while read -r line; do
  [[ $line == (-|)<-> ]]
  if [[ $line == <1-127> ]]; then
    printf \\$(([##8]line))
  else
    echo -E - $line
  fi
done
