#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_exit no_unset extended_glob pipe_fail warn_create_global

local -ir w=25 h=6

local -i i
local layer img=${(l:w*h::2:):-}

while read -rk $#img -u 0 layer; do
  for i in {1..$#img}; do
    if [[ $img[i] == 2 ]]; then
      img[i]=$layer[i]
    fi
  done
done

[[ $layer == [[:space:]]# ]]
[[ $img == [01]# ]]

for i in {1..$h}; do
  local line=$img[(i-1)*w+1,i*w]
  echo -E - ${${line//0/ }//1/#} >&2
done

echo -E - $img
