#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_return no_unset extended_glob pipe_fail warn_create_global

local min max
IFS=- read -r min max
[[ $min == <100000-999999> && $max == <100000-999999> ]]
local -i min max

local n
local -i res c

for ((n = min; n <= max; ++n)); do
  (( n[6] >= n[5] && n[5] >= n[4] && n[4] >= n[3] && n[3] >= n[2] && n[2] >= n[1] )) || continue
  for c in {1..9}; do
    [[ .$n. == *[^$c]${c}${c}[^$c]* ]] || continue
    res+=1
    break
  done
done

echo -E - $res
