#!/usr/bin/env zsh

emulate -L zsh -o err_return -o no_unset

integer min max res
IFS=- read min max

(( min >= 100000 )) || min=100000
(( max <= 999999 )) || max=999999

local n
for ((n = min; n <= max; ++n)); do
  (( n[6] >= n[5] && n[5] >= n[4] && n[4] >= n[3] && n[3] >= n[2] && n[2] >= n[1] )) || continue
  [[ .$n. == *([^1]11[^1]|[^2]22[^2]|[^3]33[^3]|[^4]44[^4]|[^5]55[^5]|[^6]66[^6]|[^7]77[^7]|[^8]88[^8]|[^9]99[^9])* ]] || continue
  (( ++res ))
done

echo - $res
