#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_exit no_unset extended_glob pipe_fail warn_create_global

zmodload zsh/mathfunc

local input="$(<&0)"
[[ $input == <-> ]]
local v=(${(s::)input})
(( $#v >= 8 ))

local -i i j m
repeat 100; do
  for i in {1..$#v}; do
    local -i x=0 k=1
    for j in {$i..$#v}; do
      if (( !--k )); then
        m='j / i'
        m='m % 2 - 2 * (m % 4 == 3)'
        k=i
      fi
      x+='v[j] * m'
    done
    v[i]=$((abs(x) % 10))
  done
done

echo -E - ${(j::)v[1,8]}
