#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_return no_unset extended_glob pipe_fail warn_create_global

local program
read -r program

function amp() (
  { echo -E - $1; exec cat } | ./icc $program
)

local -i a b c d e res=-1
local range=({0..4}) out

for a in $range; do
  for b in ${range:#($a)}; do
    for c in ${range:#($a|$b)}; do
      for d in ${range:#($a|$b|$c)}; do
        for e in ${range:#($a|$b|$c|$d)}; do
          out="$(<<<0 amp $a | amp $b | amp $c | amp $d | amp $e)"
          [[ $out == <-> ]]
          (( res > out )) || res=out
        done
      done
    done
  done
done

echo -E - $res
