#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_return no_unset extended_glob pipe_fail warn_create_global warn_nested_var

local program
read -r program

function amp() (
  { echo -E - $1; exec cat } | ./icc $program
)

local -i a b c d e x res=-1
local range=({0..4})

for a in $range; do
  for b in ${range:#($a)}; do
    for c in ${range:#($a|$b)}; do
      for d in ${range:#($a|$b|$c)}; do
        for e in ${range:#($a|$b|$c|$d)}; do
          x="$(<<<0 amp $a | amp $b | amp $c | amp $d | amp $e)"
          (( x >= 0 ))
          (( res > x )) || res=x
        done
      done
    done
  done
done

echo -E - $res
