#!/usr/bin/env zsh

emulate -L zsh
setopt no_aliases err_return no_unset extended_glob pipe_fail warn_create_global warn_nested_var

local layer c
local -i zeros=151 res

while read -rk 150 -u 0 layer; do
  local -A hist=()
  for c in {0..2}; do
    hist[$c]=${#layer//[^$c]}
  done
  if (( hist[0] < zeros )); then
    zeros=$hist[0]
    res=$((hist[1] * hist[2]))
  fi
done

(( zeros <= 150 ))
echo -E - $res
